### ISSUE TITLE
Hosted final version

### ISSUE THREAD

**Issue by alexjj** [talkpython/static-sites-with-sphinx-and-markdown-course#1]
Nice course, thanks for making it free!

I might’ve missed it but I think it would be good to get Github or Vercel or someone to host a final version so everyone can see what the end product looks like.

**Comment by mikeckennedy** [comment]
Thanks @alexjj It's not mentioned in the course, but I'd start with [netlify](https://www.netlify.com/) for deployment. Heard many good things about them.

**Comment by mikeckennedy** [comment]
Unless you're doing documentation, then something like readthedocs.

**Comment by alexjj** [comment]
Thanks - but I still think **you** should host this demo for people to see. 😅

**Comment by mikeckennedy** [comment]
I see. That isn't a bad idea. 

Unfortunately, that doesn't work. I got it to render the index.html page but it only shows the code view, not content of the CSS files. I don't have a lot of experience with GH pages, so maybe I'm missing how to get the styles to work.

**Comment by pauleveritt** [comment]
We should use RTD and stay in the Python family, IMO. It's pretty easy to wire up GitHub Actions to publish to RTD. OTOH, this repo probably won't change enough to need to be automated, so nothing more is needed IMO than the RTD file and some account on RTD.

**Comment by alexjj** [comment]
> I see. That isn't a bad idea.
> 
> Unfortunately, that doesn't work. I got it to render the index.html page but it only shows the code view, not content of the CSS files. I don't have a lot of experience with GH pages, so maybe I'm missing how to get the styles to work.

Ah that's probably Github jekyll stuff...

I forked and linked Netlify to my fork and all I had to do was set publish folder to `/docs` and it's done! https://shouldvedonethisfirst.netlify.app/

RTD is maybe more appropriate as Paul says but for a quick demo for people to see netlify does the job.

Hope I didn't waste too much of your time on this tiny detail 😅

**Comment by mikeckennedy** [comment]
Hi @alexjj and @pauleveritt.

Alex, thanks for bring this to our attention. Hosting the final version is the right thing to do.

Paul, I checked out RTD, but having it need to do the build and it talks about here's how you put your RST file rather than MD file in this place so it works seems more complex than necessary. Netlify is SO incredibly easy to us. Create an account and drop the html folder here and boom it's live is what I decided to do.

Plus, I wanted to make the hosted demo app communicate where it came from a little better by adding a custom footer sealed using Netlify over RTD. So we now have it hosted at:

https://static-sites-with-sphinx-and-markdown-demo.netlify.app/

Paul, if we need anything changed here, just let me know and I'll update it.
