### ISSUE TITLE
Autodoc & Links in the Code

### ISSUE THREAD

**Issue by gloc-mike** [talkpython/static-sites-with-sphinx-and-markdown-course#6]
In the tutorial, it states that links will be created to navigate around when `autodoc` is used to document code. I have set up `conf.py` and `api.md` for that but the only links that I'm getting are the ones in the *navigation* pane on the generated output.

[Paul's web page](https://www.jetbrains.com/pycharm/guide/tutorials/sphinx_sites/documentation/) on this course at says:

> It's visually attractive. More than that, though...it's semantically rich: links to navigate around, styling for the structure, and more.

Yes, it's *semantically rich*, etc., but I see no **links to navigate around** in the code.

I have set up `conf.py` with the prerequisite extensions:

```
extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx_autodoc_typehints",
    "sphinx.ext.intersphinx",
]
```

And created `api.md`:

```
    # About `MyDemo`

    Let's take a look at this Python class.

    ```{eval-rst}
     .. autoclass:: my_demo.MyDemo
       :members:
     ```

     # About `MyClass`

     ```{eval-rst}
     .. autoclass:: my_demo.MyClass
        :members:
     ```
```

The Python file `my_demo.py` looks like this:

```
class MyDemo:
    """ A *great* demo """
    def __init__(self, name):
        self.name = name

    def hello(self):
        """ Be friendly """
        return f"Hello {self.name}"

class MyClass:
    """ A *great* demo """

    def __init__(self, name):
        self.name = name

    def hello(self, greeting: str) -> str:
        """ The canonical hello world example.

        A *longer* description with some **RST**.

        Args:
            name: The person to say hello to.
        Returns:
            str: The greeting
         """
        return f"{greeting} {self.name}"
```

The resultant HTML page looks like this but nothing in the code has links:
![Screen Shot 2022-01-22 at 5 13 49 pm](https://user-images.githubusercontent.com/2324626/150627487-b547db05-b851-4913-9113-ebdfa9adac64.png)

Is that correct? Or am I missing something?

Thanks
Michael

**Comment by gloc-mike** [comment]
Oh I think you mean **_link targets_**, right? Not links within the code itself.

**Comment by pauleveritt** [comment]
I should have been more specific and provided an example, such as [Python's `pathlib` docs](https://docs.python.org/3/library/pathlib.html#methods-and-properties). In the docstrings there, you can link to other symbols and navigate around.

Your own code's symbols becomes roles which can be linked to as well. These behave in the semantically-rich way as other roles: short names, warnings if the target isn't found, can target HTML/PDF/etc.

**Comment by pauleveritt** [comment]
I'll redo that comment when I can link to a better example.

**Comment by pauleveritt** [comment]
autodoc can make sense out of docstrings and for example response values in a "semantically-rich" way. What do I mean by this? Instead of just strings like `*my_demo.MyDemo*` to point to a class with an italics, it inserts docutils nodes for the code reference and generates roles that can be link targets.

This results in styleable output across HTML/PDF/man/etc. targets. As the course showed, it also generates roles that can be linked to with all the link machinery.

But docstrings can also do these references (alas, RST only for now, though being worked on). And things like `sphinx_autodoc_typehints` can make links in parameters.

Here is a [re-written my_demo.py](https://gist.github.com/932524346e8dc2dbb600e673d6ae9641) that introduces a second class. In `MyDemo`, two changes: the docstring does a `:py:meth:`. Also, the method returns a `Message`.

Attached is a screenshot showing that this generates a link to the "role" for `Message`.

Here is a [rewritten `api.md`](https://gist.github.com/630320d1c77dd3a951d36611adbea54c) `api.md` which switches from autoclass to automodule to get both of them.

**Comment by gloc-mike** [comment]
Fantastic! Thanks for the updated example. That's brilliant!
